// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVaQ3VBDzerR5cMqcFn2KoggmuZC4ut-c',
    appId: '1:558837968429:web:1521f76c45ed68a59312a4',
    messagingSenderId: '558837968429',
    projectId: 'database-posyandu-71386',
    authDomain: 'database-posyandu-71386.firebaseapp.com',
    storageBucket: 'database-posyandu-71386.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6HzJ_iJmOjI9CkKjB-tgUFoQOTawzPdE',
    appId: '1:558837968429:android:b70b0b0cd89953a99312a4',
    messagingSenderId: '558837968429',
    projectId: 'database-posyandu-71386',
    storageBucket: 'database-posyandu-71386.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuO-tuqGzyVozBWn2XOlp6hdUokBJMvaY',
    appId: '1:558837968429:ios:f0c32b95d1f9330e9312a4',
    messagingSenderId: '558837968429',
    projectId: 'database-posyandu-71386',
    storageBucket: 'database-posyandu-71386.appspot.com',
    iosClientId: '558837968429-tn7276t3114lm67bhunh8nouqu1qjjmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.posyanduCipayung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuO-tuqGzyVozBWn2XOlp6hdUokBJMvaY',
    appId: '1:558837968429:ios:f0c32b95d1f9330e9312a4',
    messagingSenderId: '558837968429',
    projectId: 'database-posyandu-71386',
    storageBucket: 'database-posyandu-71386.appspot.com',
    iosClientId: '558837968429-tn7276t3114lm67bhunh8nouqu1qjjmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.posyanduCipayung',
  );
}
